### ISSUE TITLE
It looks like generation of autoreply.json does not work with the latest version

### ISSUE THREAD

**Issue by oerjann** [innovara/autoreply#13]
# ./autoreply.py -j
Traceback (most recent call last):
  File "./autoreply.py", line 314, in <module>
    main()
  File "./autoreply.py", line 279, in main
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./autoreply.py", line 317, in <module>
    log("Unhandled exception: %s\n%s" % (exc.__class__.__name__, traceback.format_exc()))
  File "./autoreply.py", line 17, in log
    if logging == True:
NameError: name 'logging' is not defined

**Comment by oerjann** [comment]
Thank you, it works now. At first I didn't find the new configuration file, but then I saw in he documentation that the location of the new configuration file is ~/ It might be better and avoid some confusion if the generated configuration file is outputted int the same directory as the script is ran from.

**Comment by innovara** [comment]
It was a while ago when I tried present working directory and, if I remember correctly, the problem was that when the script runs as a filter, which is its ultimate purpose, it would not be able to use paths that way to load settings and so on. Hence I decided to use the home directory approach which as per the documentation, should be that of a special user for this purpose and nothing else. It might have been something else, but what I do remember is trying that approach which I would prefer as well and then changing course because of it presenting some problems.
