### ISSUE TITLE
Does this work for a whole domain?

### ISSUE THREAD

**Issue by cklabautermann** [innovara/autoreply#3]
I want to notify senders that mails to a specific domain will be discarded soon.
I know this is called backscattering, but it is what I am supposed to do.
Can I use the line "email": "foo@bar" as "email": "*@bar"?
Thanks in advance

**Comment by innovara** [comment]
Hi,

Not in its current form and with the proposed configuration. The script currently matches email addresses listed in autoreply.json against the recipient email addresses of the incoming email (see last line).
```
def autoreply(smtp, sender, recipients):
  '''Sends auto-reply email from recipient to sender when the recipient is in ~/autoreply.json.'''
  data = open_json()
  # Iterates through JSON autoreply objects
  for recipient in data['autoreply']:
    # Checks if an email in ~/autoreply.json is in the list of recipients of the original email
    if recipient['email'] in recipients:
```
You'd have to do some parsing to extract the domains of the incoming email recipients and output them to a new list before you were ready to enter the if loop using that new list. You wouldn't use *@bar, just @bar.

You might have to make more changes, I did this a while ago.

Then there is the issue of how the incoming emails enter the script. I think you'd need a `regexp` lookup table with the expression that matches the discontinued domain instead of a `hash` lookup table. But maybe you can use wildcards so I'd first try `hash` with @bar and investigate other options if that didn't work.

I did this for a client and I no longer have access to an environment to test any of the above. If enlisting professional support is within the scope of your options to accomplish your goal, I'd be very happy to help.
